# Generated by Django 5.0.1 on 2024-02-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_book_author_photo_book_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rented',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
